// Mocks generated by Mockito 5.4.6 from annotations
// in coves_flutter/test/providers/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coves_flutter/models/coves_session.dart' as _i2;
import 'package:coves_flutter/services/coves_auth_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCovesSession_0 extends _i1.SmartFake implements _i2.CovesSession {
  _FakeCovesSession_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CovesAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCovesAuthService extends _i1.Mock implements _i3.CovesAuthService {
  MockCovesAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.CovesSession> signIn(String? handle) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [handle]),
            returnValue: _i4.Future<_i2.CovesSession>.value(
              _FakeCovesSession_0(this, Invocation.method(#signIn, [handle])),
            ),
          )
          as _i4.Future<_i2.CovesSession>);

  @override
  _i4.Future<_i2.CovesSession?> restoreSession() =>
      (super.noSuchMethod(
            Invocation.method(#restoreSession, []),
            returnValue: _i4.Future<_i2.CovesSession?>.value(),
          )
          as _i4.Future<_i2.CovesSession?>);

  @override
  _i4.Future<_i2.CovesSession> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<_i2.CovesSession>.value(
              _FakeCovesSession_0(this, Invocation.method(#refreshToken, [])),
            ),
          )
          as _i4.Future<_i2.CovesSession>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
