// Mocks generated by Mockito 5.4.6 from annotations
// in coves_flutter/test/providers/comments_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:typed_data' as _i12;
import 'dart:ui' as _i10;

import 'package:coves_flutter/models/comment.dart' as _i3;
import 'package:coves_flutter/models/community.dart' as _i4;
import 'package:coves_flutter/models/post.dart' as _i2;
import 'package:coves_flutter/models/user_profile.dart' as _i5;
import 'package:coves_flutter/providers/auth_provider.dart' as _i8;
import 'package:coves_flutter/providers/vote_provider.dart' as _i13;
import 'package:coves_flutter/services/comment_service.dart' as _i7;
import 'package:coves_flutter/services/coves_api_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTimelineResponse_0 extends _i1.SmartFake
    implements _i2.TimelineResponse {
  _FakeTimelineResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentsResponse_1 extends _i1.SmartFake
    implements _i3.CommentsResponse {
  _FakeCommentsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommunitiesResponse_2 extends _i1.SmartFake
    implements _i4.CommunitiesResponse {
  _FakeCommunitiesResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreatePostResponse_3 extends _i1.SmartFake
    implements _i4.CreatePostResponse {
  _FakeCreatePostResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateCommunityResponse_4 extends _i1.SmartFake
    implements _i4.CreateCommunityResponse {
  _FakeCreateCommunityResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_5 extends _i1.SmartFake implements _i5.UserProfile {
  _FakeUserProfile_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeActorCommentsResponse_6 extends _i1.SmartFake
    implements _i3.ActorCommentsResponse {
  _FakeActorCommentsResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProfileResponse_7 extends _i1.SmartFake
    implements _i6.UpdateProfileResponse {
  _FakeUpdateProfileResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCreateCommentResponse_8 extends _i1.SmartFake
    implements _i7.CreateCommentResponse {
  _FakeCreateCommentResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i8.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i9.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i9.Future<String?>.value(),
          )
          as _i9.Future<String?>);

  @override
  _i9.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signIn(String? handle) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [handle]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CovesApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCovesApiService extends _i1.Mock implements _i6.CovesApiService {
  MockCovesApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.TimelineResponse> getTimeline({
    String? sort = 'hot',
    String? timeframe,
    int? limit = 15,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeline, [], {
              #sort: sort,
              #timeframe: timeframe,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i9.Future<_i2.TimelineResponse>.value(
              _FakeTimelineResponse_0(
                this,
                Invocation.method(#getTimeline, [], {
                  #sort: sort,
                  #timeframe: timeframe,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.TimelineResponse>);

  @override
  _i9.Future<_i2.TimelineResponse> getDiscover({
    String? sort = 'hot',
    String? timeframe,
    int? limit = 15,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiscover, [], {
              #sort: sort,
              #timeframe: timeframe,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i9.Future<_i2.TimelineResponse>.value(
              _FakeTimelineResponse_0(
                this,
                Invocation.method(#getDiscover, [], {
                  #sort: sort,
                  #timeframe: timeframe,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.TimelineResponse>);

  @override
  _i9.Future<_i3.CommentsResponse> getComments({
    required String? postUri,
    String? sort = 'hot',
    String? timeframe,
    int? depth = 10,
    int? limit = 50,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [], {
              #postUri: postUri,
              #sort: sort,
              #timeframe: timeframe,
              #depth: depth,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i9.Future<_i3.CommentsResponse>.value(
              _FakeCommentsResponse_1(
                this,
                Invocation.method(#getComments, [], {
                  #postUri: postUri,
                  #sort: sort,
                  #timeframe: timeframe,
                  #depth: depth,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.CommentsResponse>);

  @override
  _i9.Future<_i4.CommunitiesResponse> listCommunities({
    int? limit = 50,
    String? cursor,
    String? sort = 'popular',
    bool? subscribed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listCommunities, [], {
              #limit: limit,
              #cursor: cursor,
              #sort: sort,
              #subscribed: subscribed,
            }),
            returnValue: _i9.Future<_i4.CommunitiesResponse>.value(
              _FakeCommunitiesResponse_2(
                this,
                Invocation.method(#listCommunities, [], {
                  #limit: limit,
                  #cursor: cursor,
                  #sort: sort,
                  #subscribed: subscribed,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.CommunitiesResponse>);

  @override
  _i9.Future<_i4.CreatePostResponse> createPost({
    required String? community,
    String? title,
    String? content,
    _i4.ExternalEmbedInput? embed,
    List<String>? langs,
    _i4.SelfLabels? labels,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #community: community,
              #title: title,
              #content: content,
              #embed: embed,
              #langs: langs,
              #labels: labels,
            }),
            returnValue: _i9.Future<_i4.CreatePostResponse>.value(
              _FakeCreatePostResponse_3(
                this,
                Invocation.method(#createPost, [], {
                  #community: community,
                  #title: title,
                  #content: content,
                  #embed: embed,
                  #langs: langs,
                  #labels: labels,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.CreatePostResponse>);

  @override
  _i9.Future<_i4.CreateCommunityResponse> createCommunity({
    required String? name,
    required String? displayName,
    required String? description,
    String? visibility = 'public',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createCommunity, [], {
              #name: name,
              #displayName: displayName,
              #description: description,
              #visibility: visibility,
            }),
            returnValue: _i9.Future<_i4.CreateCommunityResponse>.value(
              _FakeCreateCommunityResponse_4(
                this,
                Invocation.method(#createCommunity, [], {
                  #name: name,
                  #displayName: displayName,
                  #description: description,
                  #visibility: visibility,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.CreateCommunityResponse>);

  @override
  _i9.Future<_i5.UserProfile> getProfile({required String? actor}) =>
      (super.noSuchMethod(
            Invocation.method(#getProfile, [], {#actor: actor}),
            returnValue: _i9.Future<_i5.UserProfile>.value(
              _FakeUserProfile_5(
                this,
                Invocation.method(#getProfile, [], {#actor: actor}),
              ),
            ),
          )
          as _i9.Future<_i5.UserProfile>);

  @override
  _i9.Future<_i2.TimelineResponse> getAuthorPosts({
    required String? actor,
    String? filter,
    String? community,
    int? limit = 15,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAuthorPosts, [], {
              #actor: actor,
              #filter: filter,
              #community: community,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i9.Future<_i2.TimelineResponse>.value(
              _FakeTimelineResponse_0(
                this,
                Invocation.method(#getAuthorPosts, [], {
                  #actor: actor,
                  #filter: filter,
                  #community: community,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i9.Future<_i2.TimelineResponse>);

  @override
  _i9.Future<_i3.ActorCommentsResponse> getActorComments({
    required String? actor,
    String? community,
    int? limit = 50,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActorComments, [], {
              #actor: actor,
              #community: community,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i9.Future<_i3.ActorCommentsResponse>.value(
              _FakeActorCommentsResponse_6(
                this,
                Invocation.method(#getActorComments, [], {
                  #actor: actor,
                  #community: community,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i9.Future<_i3.ActorCommentsResponse>);

  @override
  _i9.Future<String> subscribeToCommunity({required String? community}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToCommunity, [], {
              #community: community,
            }),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#subscribeToCommunity, [], {
                  #community: community,
                }),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> unsubscribeFromCommunity({required String? community}) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromCommunity, [], {
              #community: community,
            }),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i4.CreateCommunityResponse> updateCommunity({
    required String? communityDid,
    required _i12.Uint8List? imageBytes,
    required String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCommunity, [], {
              #communityDid: communityDid,
              #imageBytes: imageBytes,
              #mimeType: mimeType,
            }),
            returnValue: _i9.Future<_i4.CreateCommunityResponse>.value(
              _FakeCreateCommunityResponse_4(
                this,
                Invocation.method(#updateCommunity, [], {
                  #communityDid: communityDid,
                  #imageBytes: imageBytes,
                  #mimeType: mimeType,
                }),
              ),
            ),
          )
          as _i9.Future<_i4.CreateCommunityResponse>);

  @override
  _i9.Future<_i6.UpdateProfileResponse> updateProfile({
    String? displayName,
    String? bio,
    _i12.Uint8List? avatarBytes,
    String? avatarMimeType,
    _i12.Uint8List? bannerBytes,
    String? bannerMimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #bio: bio,
              #avatarBytes: avatarBytes,
              #avatarMimeType: avatarMimeType,
              #bannerBytes: bannerBytes,
              #bannerMimeType: bannerMimeType,
            }),
            returnValue: _i9.Future<_i6.UpdateProfileResponse>.value(
              _FakeUpdateProfileResponse_7(
                this,
                Invocation.method(#updateProfile, [], {
                  #displayName: displayName,
                  #bio: bio,
                  #avatarBytes: avatarBytes,
                  #avatarMimeType: avatarMimeType,
                  #bannerBytes: bannerBytes,
                  #bannerMimeType: bannerMimeType,
                }),
              ),
            ),
          )
          as _i9.Future<_i6.UpdateProfileResponse>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VoteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoteProvider extends _i1.Mock implements _i13.VoteProvider {
  MockVoteProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.VoteState? getVoteState(String? postUri) =>
      (super.noSuchMethod(Invocation.method(#getVoteState, [postUri]))
          as _i13.VoteState?);

  @override
  bool isLiked(String? postUri) =>
      (super.noSuchMethod(
            Invocation.method(#isLiked, [postUri]),
            returnValue: false,
          )
          as bool);

  @override
  bool isPending(String? postUri) =>
      (super.noSuchMethod(
            Invocation.method(#isPending, [postUri]),
            returnValue: false,
          )
          as bool);

  @override
  int getAdjustedScore(String? postUri, int? serverScore) =>
      (super.noSuchMethod(
            Invocation.method(#getAdjustedScore, [postUri, serverScore]),
            returnValue: 0,
          )
          as int);

  @override
  _i9.Future<bool> toggleVote({
    required String? postUri,
    required String? postCid,
    String? direction = 'up',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleVote, [], {
              #postUri: postUri,
              #postCid: postCid,
              #direction: direction,
            }),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  void setInitialVoteState({
    required String? postUri,
    String? voteDirection,
    String? voteUri,
  }) => super.noSuchMethod(
    Invocation.method(#setInitialVoteState, [], {
      #postUri: postUri,
      #voteDirection: voteDirection,
      #voteUri: voteUri,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CommentService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCommentService extends _i1.Mock implements _i7.CommentService {
  MockCommentService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.CreateCommentResponse> createComment({
    required String? rootUri,
    required String? rootCid,
    required String? parentUri,
    required String? parentCid,
    required String? content,
    List<_i2.RichTextFacet>? contentFacets,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #rootUri: rootUri,
              #rootCid: rootCid,
              #parentUri: parentUri,
              #parentCid: parentCid,
              #content: content,
              #contentFacets: contentFacets,
            }),
            returnValue: _i9.Future<_i7.CreateCommentResponse>.value(
              _FakeCreateCommentResponse_8(
                this,
                Invocation.method(#createComment, [], {
                  #rootUri: rootUri,
                  #rootCid: rootCid,
                  #parentUri: parentUri,
                  #parentCid: parentCid,
                  #content: content,
                  #contentFacets: contentFacets,
                }),
              ),
            ),
          )
          as _i9.Future<_i7.CreateCommentResponse>);
}
