// Mocks generated by Mockito 5.4.6 from annotations
// in coves_flutter/test/providers/comments_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:coves_flutter/models/comment.dart' as _i3;
import 'package:coves_flutter/models/post.dart' as _i2;
import 'package:coves_flutter/providers/auth_provider.dart' as _i5;
import 'package:coves_flutter/providers/vote_provider.dart' as _i9;
import 'package:coves_flutter/services/coves_api_service.dart' as _i8;
import 'package:coves_flutter/services/vote_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTimelineResponse_0 extends _i1.SmartFake
    implements _i2.TimelineResponse {
  _FakeTimelineResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCommentsResponse_1 extends _i1.SmartFake
    implements _i3.CommentsResponse {
  _FakeCommentsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVoteResponse_2 extends _i1.SmartFake implements _i4.VoteResponse {
  _FakeVoteResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i5.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<String?> getAccessToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signIn(String? handle) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [handle]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CovesApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCovesApiService extends _i1.Mock implements _i8.CovesApiService {
  MockCovesApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.TimelineResponse> getTimeline({
    String? sort = 'hot',
    String? timeframe,
    int? limit = 15,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTimeline, [], {
              #sort: sort,
              #timeframe: timeframe,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i6.Future<_i2.TimelineResponse>.value(
              _FakeTimelineResponse_0(
                this,
                Invocation.method(#getTimeline, [], {
                  #sort: sort,
                  #timeframe: timeframe,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.TimelineResponse>);

  @override
  _i6.Future<_i2.TimelineResponse> getDiscover({
    String? sort = 'hot',
    String? timeframe,
    int? limit = 15,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDiscover, [], {
              #sort: sort,
              #timeframe: timeframe,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i6.Future<_i2.TimelineResponse>.value(
              _FakeTimelineResponse_0(
                this,
                Invocation.method(#getDiscover, [], {
                  #sort: sort,
                  #timeframe: timeframe,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.TimelineResponse>);

  @override
  _i6.Future<_i3.CommentsResponse> getComments({
    required String? postUri,
    String? sort = 'hot',
    String? timeframe,
    int? depth = 10,
    int? limit = 50,
    String? cursor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [], {
              #postUri: postUri,
              #sort: sort,
              #timeframe: timeframe,
              #depth: depth,
              #limit: limit,
              #cursor: cursor,
            }),
            returnValue: _i6.Future<_i3.CommentsResponse>.value(
              _FakeCommentsResponse_1(
                this,
                Invocation.method(#getComments, [], {
                  #postUri: postUri,
                  #sort: sort,
                  #timeframe: timeframe,
                  #depth: depth,
                  #limit: limit,
                  #cursor: cursor,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.CommentsResponse>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VoteProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoteProvider extends _i1.Mock implements _i9.VoteProvider {
  MockVoteProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i9.VoteState? getVoteState(String? postUri) =>
      (super.noSuchMethod(Invocation.method(#getVoteState, [postUri]))
          as _i9.VoteState?);

  @override
  bool isLiked(String? postUri) =>
      (super.noSuchMethod(
            Invocation.method(#isLiked, [postUri]),
            returnValue: false,
          )
          as bool);

  @override
  bool isPending(String? postUri) =>
      (super.noSuchMethod(
            Invocation.method(#isPending, [postUri]),
            returnValue: false,
          )
          as bool);

  @override
  int getAdjustedScore(String? postUri, int? serverScore) =>
      (super.noSuchMethod(
            Invocation.method(#getAdjustedScore, [postUri, serverScore]),
            returnValue: 0,
          )
          as int);

  @override
  _i6.Future<bool> toggleVote({
    required String? postUri,
    required String? postCid,
    String? direction = 'up',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleVote, [], {
              #postUri: postUri,
              #postCid: postCid,
              #direction: direction,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void setInitialVoteState({
    required String? postUri,
    String? voteDirection,
    String? voteUri,
  }) => super.noSuchMethod(
    Invocation.method(#setInitialVoteState, [], {
      #postUri: postUri,
      #voteDirection: voteDirection,
      #voteUri: voteUri,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void loadInitialVotes(Map<String, _i4.VoteInfo>? votes) => super.noSuchMethod(
    Invocation.method(#loadInitialVotes, [votes]),
    returnValueForMissingStub: null,
  );

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VoteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoteService extends _i1.Mock implements _i4.VoteService {
  MockVoteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<Map<String, _i4.VoteInfo>> getUserVotes() =>
      (super.noSuchMethod(
            Invocation.method(#getUserVotes, []),
            returnValue: _i6.Future<Map<String, _i4.VoteInfo>>.value(
              <String, _i4.VoteInfo>{},
            ),
          )
          as _i6.Future<Map<String, _i4.VoteInfo>>);

  @override
  _i6.Future<_i4.VoteResponse> createVote({
    required String? postUri,
    required String? postCid,
    String? direction = 'up',
    String? existingVoteRkey,
    String? existingVoteDirection,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createVote, [], {
              #postUri: postUri,
              #postCid: postCid,
              #direction: direction,
              #existingVoteRkey: existingVoteRkey,
              #existingVoteDirection: existingVoteDirection,
            }),
            returnValue: _i6.Future<_i4.VoteResponse>.value(
              _FakeVoteResponse_2(
                this,
                Invocation.method(#createVote, [], {
                  #postUri: postUri,
                  #postCid: postCid,
                  #direction: direction,
                  #existingVoteRkey: existingVoteRkey,
                  #existingVoteDirection: existingVoteDirection,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.VoteResponse>);
}
