// Mocks generated by Mockito 5.4.6 from annotations
// in coves_flutter/test/services/vote_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:atproto_oauth_flutter/src/oauth/oauth_server_agent.dart' as _i2;
import 'package:atproto_oauth_flutter/src/session/oauth_session.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeOAuthServerAgent_0 extends _i1.SmartFake
    implements _i2.OAuthServerAgent {
  _FakeOAuthServerAgent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSessionGetterInterface_1 extends _i1.SmartFake
    implements _i3.SessionGetterInterface {
  _FakeSessionGetterInterface_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTokenInfo_2 extends _i1.SmartFake implements _i3.TokenInfo {
  _FakeTokenInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OAuthSession].
///
/// See the documentation for Mockito's code generation for more information.
class MockOAuthSession extends _i1.Mock implements _i3.OAuthSession {
  MockOAuthSession() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OAuthServerAgent get server =>
      (super.noSuchMethod(
            Invocation.getter(#server),
            returnValue: _FakeOAuthServerAgent_0(
              this,
              Invocation.getter(#server),
            ),
          )
          as _i2.OAuthServerAgent);

  @override
  String get sub =>
      (super.noSuchMethod(
            Invocation.getter(#sub),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#sub)),
          )
          as String);

  @override
  _i3.SessionGetterInterface get sessionGetter =>
      (super.noSuchMethod(
            Invocation.getter(#sessionGetter),
            returnValue: _FakeSessionGetterInterface_1(
              this,
              Invocation.getter(#sessionGetter),
            ),
          )
          as _i3.SessionGetterInterface);

  @override
  String get did =>
      (super.noSuchMethod(
            Invocation.getter(#did),
            returnValue: _i5.dummyValue<String>(this, Invocation.getter(#did)),
          )
          as String);

  @override
  Map<String, dynamic> get serverMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#serverMetadata),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<_i3.TokenInfo> getTokenInfo([dynamic refresh = 'auto']) =>
      (super.noSuchMethod(
            Invocation.method(#getTokenInfo, [refresh]),
            returnValue: _i6.Future<_i3.TokenInfo>.value(
              _FakeTokenInfo_2(
                this,
                Invocation.method(#getTokenInfo, [refresh]),
              ),
            ),
          )
          as _i6.Future<_i3.TokenInfo>);

  @override
  _i6.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i4.Response> fetchHandler(
    String? pathname, {
    String? method = 'GET',
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchHandler,
              [pathname],
              {#method: method, #headers: headers, #body: body},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_3(
                this,
                Invocation.method(
                  #fetchHandler,
                  [pathname],
                  {#method: method, #headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
